services:
  goteth:
    build:
      context: ./
      dockerfile: Dockerfile
    init: true
    container_name: goteth
    command: >-
      blocks
      --log-level=${GOTETH_LOG_LEVEL}
      --bn-endpoint=${GOTETH_BN_ENDPOINT}
      --el-endpoint=${GOTETH_ANALYZER_EL_ENDPOINT:-}
      --init-slot=${GOTETH_ANALYZER_INIT_SLOT}
      --final-slot=${GOTETH_ANALYZER_FINAL_SLOT}
      --db-url=${GOTETH_DB_URL}
      --workers-num=${GOTETH_ANALYZER_WORKERS_NUM}
      --db-workers-num=${GOTETH_ANALYZER_DB_WORKERS_NUM}
      --download-mode=${GOTETH_ANALYZER_DOWNLOAD_MODE}
      --metrics=${GOTETH_ANALYZER_METRICS}
      --prometheus-port=${GOTETH_ANALYZER_PROMETHEUS_PORT:-9081}
      --rewards-aggregation-epochs=${GOTETH_ANALYZER_REWARDS_AGGREGATION_EPOCHS:-1}
      --max-request-retries=${GOTETH_ANALYZER_MAX_REQUEST_RETRIES:-5}
      --beacon-contract-address=${GOTETH_ANALYZER_BEACON_CONTRACT_ADDRESS:-mainnet}
    network_mode: "host"
    restart: "always"